version: "3"


services:
  postgres_db:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=devpass
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    depends_on:
      - postgres_db
    ports:
      - "8000:8000"
  redis:
    image: redis
    ports:
      - "6379:6379"
    depends_on:
      - web
#  celery_beat:
#    build:
#      context: .
#    volumes:
#      - ./:/usr/src/app
#    command: ["celery", "-A", "news_board", "beat"]
#    depends_on:
#      - redis
#      - postgres_db
#      - web
#  celery_worker:
#    build:
#      context: .
#    volumes:
#      - ./:/usr/src/app
#    command: ["celery", "-A", "news_board", "worker", "-l", "INFO"]
#    depends_on:
#      - redis
#      - postgres_db
#      - web
